# Generated by Django 5.2.7 on 2025-10-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeOpcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos de Opções',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Use este campo se o produto tiver um preço único, que não varia por opção.', max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='cardapio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ValoresDeOpcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser somado ao preço final se esta opção for escolhida (ex: borda recheada).', max_digits=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='cardapio.grupodeopcoes')),
            ],
            options={
                'verbose_name_plural': 'Valores de Opções',
            },
        ),
        migrations.CreateModel(
            name='PrecosPorOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_opcoes', to='cardapio.produto')),
                ('valor_opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='cardapio.valoresdeopcoes')),
            ],
            options={
                'verbose_name_plural': 'Preços por Opção',
                'unique_together': {('produto', 'valor_opcao')},
            },
        ),
    ]
