# Generated by Django 5.2.7 on 2025-10-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='permite_adicionais',
            field=models.BooleanField(default=False, help_text='Marque se produtos desta categoria podem ter itens adicionais.'),
        ),
    ]
