# Generated by Django 5.2.7 on 2025-10-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_categoria_permite_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='opcoes_obrigatorias',
            field=models.ManyToManyField(blank=True, help_text='Anexe grupos de opções extras que são obrigatórias (ex: Sabor do Suco).', related_name='produtos_com_opcao_obrigatoria', to='cardapio.grupodeopcoes'),
        ),
        migrations.AddField(
            model_name='valoresdeopcoes',
            name='is_adicional',
            field=models.BooleanField(default=False, help_text='Marque se esta opção é um adicional (ex: Bacon Extra) e não uma opção principal (ex: Tamanho).'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Use se o preço for único.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valoresdeopcoes',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_de_opcoes', to='cardapio.grupodeopcoes'),
        ),
        migrations.AlterField(
            model_name='valoresdeopcoes',
            name='preco_adicional',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser somado se esta opção for escolhida (ex: adicionais).', max_digits=10),
        ),
    ]
