# Generated by Django 5.2.7 on 2025-10-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('anotado', 'Anotado'), ('em_preparo', 'Em Preparo'), ('entregue', 'Entregue'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='anotado', max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('observacoes', models.TextField(blank=True, help_text='Ex: sem cebola, ponto da carne, etc.', null=True)),
                ('opcoes_selecionadas', models.ManyToManyField(blank=True, to='cardapio.valoresdeopcoes')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
