# Generated by Django 5.2.7 on 2025-10-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_garcom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, help_text='Nome de referência para o pedido, ex: Mesa do Renato', max_length=100, null=True),
        ),
    ]
