# Generated by Django 5.2.7 on 2025-10-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_nome_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
