# Generated by Django 5.2.7 on 2025-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_itempedido_preco_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('anotado', 'Anotado'), ('em_preparo', 'Em Preparo'), ('entregue', 'Entregue'), ('solicitado_conta', 'Solicitado Conta'), ('conta_impressa', 'Conta Impressa'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='anotado', max_length=20),
        ),
    ]
